"""Offline grounded responder.

This provider generates nothing. It assembles an answer from the sentences in the
retrieved passages that actually address the question, and it says plainly that
it did so.

That matters more than it might appear. A prototype that quietly substitutes
canned text for a language model teaches the wrong thing about AI systems. This
one is useful offline while remaining honest about which part of the pipeline is
running — and because every sentence is quoted from a cited source, no figure or
claim can appear that the corpus does not contain.
"""

from __future__ import annotations

from dataclasses import dataclass
from re import compile as compile_pattern

from app.services.text_utils import content_tokens, normalise, split_sentences, token_overlap

from .base import GenerationRequest, LLMProvider

MAX_UNITS = 6
MAX_PROSE_UNITS = 2
MAX_POINT_UNITS = 4
MIN_UNIT_CHARS = 45
MAX_UNIT_CHARS = 320

NO_COVERAGE = (
    "The knowledge base does not appear to cover that question, so no grounded "
    "answer can be assembled from it. Try rephrasing around a topic Verdant holds "
    "material on — waste, water, energy, transport, consumption, biodiversity, "
    "climate action or the Sustainable Development Goals."
)

NO_PROVIDER_NOTE = (
    "This response was assembled directly from the retrieved source text rather "
    "than generated by a language model."
)


@dataclass(frozen=True)
class _Unit:
    """A candidate sentence, with where it came from and how well it scored."""

    text: str
    passage_index: int
    position: int
    is_point: bool
    score: float


LIST_MARKER = compile_pattern(r"^(?:[-*+]|\d+[.)]|[a-z][.)])\s+")
HEADING_LINE = compile_pattern(r"^#{2,6}\s")
TABLE_RULE = compile_pattern(r"^\|[\s:|-]+\|$")


def _clean(text: str) -> str:
    """Remove inline Markdown emphasis and collapse whitespace."""
    text = text.replace("**", "").replace("`", "").replace("__", "")
    return " ".join(text.split())


def _list_marker(line: str) -> str | None:
    match = LIST_MARKER.match(line)
    return match.group(0) if match else None


def _table_row(line: str) -> str:
    """Render a Markdown table row as a readable phrase."""
    cells = [_clean(cell) for cell in line.strip().strip("|").split("|")]
    return " — ".join(cell for cell in cells if cell)


def _block_units(passage: str) -> list[tuple[str, bool]]:
    """Split a passage into (text, is_point) blocks.

    Markdown lists wrap across lines, so an indented continuation line belongs to
    the item above it rather than starting a new paragraph. Tracking that is what
    keeps numbered guidance from being chopped into fragments.
    """
    lines = passage.splitlines()

    # The chunker prefixes passages with "Title — Heading" as retrieval metadata;
    # repeating it inside an answer reads badly, so it is dropped.
    first = lines[0].strip() if lines else ""
    if first and not first.startswith(("-", "*", "|")) and not HEADING_LINE.match(first):
        lines = lines[1:]

    units: list[tuple[str, bool]] = []
    buffer: list[str] = []
    buffer_is_point = False

    def flush() -> None:
        nonlocal buffer, buffer_is_point
        if buffer:
            joined = _clean(" ".join(buffer))
            # A short block ending in a colon is a lead-in to the list that
            # follows, not a statement — quoting it alone reads as a fragment.
            is_lead_in = joined.endswith(":") and len(joined) < 140
            if joined and not is_lead_in:
                units.append((joined, buffer_is_point))
        buffer = []
        buffer_is_point = False

    for line in lines:
        stripped = line.strip()

        if not stripped:
            flush()
            continue

        if HEADING_LINE.match(stripped):
            flush()
            continue

        indented = line[:1].isspace()

        # Table separator rows carry no meaning.
        if TABLE_RULE.match(stripped):
            continue

        if stripped.startswith("|"):
            flush()
            row = _table_row(stripped)
            if row:
                units.append((row, True))
            continue

        marker = _list_marker(stripped)
        if marker:
            flush()
            buffer = [stripped[len(marker) :]]
            buffer_is_point = True
            continue

        if indented and buffer:
            # Continuation of the item or paragraph above.
            buffer.append(stripped)
            continue

        if buffer_is_point:
            flush()

        buffer.append(stripped)

    flush()
    return units


def _units_from_passage(passage: str, passage_index: int) -> list[_Unit]:
    """Break a passage into sentence-sized units, preserving bullet points."""
    collected: list[_Unit] = []

    for position, (block, is_point) in enumerate(_block_units(passage)):
        if not block:
            continue

        # Long prose blocks are split so a single relevant sentence can be picked.
        sentences = (
            split_sentences(block) if (len(block) > MAX_UNIT_CHARS and not is_point) else [block]
        )

        for sentence in sentences:
            if len(sentence) < MIN_UNIT_CHARS:
                continue
            collected.append(
                _Unit(
                    text=sentence,
                    passage_index=passage_index,
                    position=position,
                    is_point=is_point,
                    score=0.0,
                )
            )

    return collected


def _score(units: list[_Unit], question: str) -> list[_Unit]:
    """Rank units by how much of the question they address."""
    question_tokens = content_tokens(question)
    if not question_tokens:
        return units

    scored: list[_Unit] = []
    for unit in units:
        overlap = token_overlap(question_tokens, content_tokens(unit.text))

        # Bullet points are usually the actionable line in a passage, so they
        # get a small nudge over surrounding prose. A decaying bonus for early
        # units keeps the opening sentence of a section in contention, since it
        # usually introduces the topic. Passages are ranked by relevance already,
        # so an earlier passage carries a slight advantage over a later one.
        bonus = (
            (0.10 if unit.is_point else 0.0)
            + (0.08 / (1.0 + unit.position))
            + (0.12 / (1.0 + unit.passage_index))
        )

        scored.append(
            _Unit(
                text=unit.text,
                passage_index=unit.passage_index,
                position=unit.position,
                is_point=unit.is_point,
                score=overlap + bonus,
            )
        )

    return scored


PROSE_PASSAGE_LIMIT = 2


def _select(units: list[_Unit], limit: int = MAX_UNITS) -> list[_Unit]:
    """Pick the best units, then restore their original reading order.

    Prose and bullet points are budgeted separately so an answer does not become
    a wall of one or the other, and so a single verbose passage cannot crowd out
    the actionable lines.

    Prose is additionally restricted to the leading passages. A bullet point is
    self-contained, but a sentence pulled from deep in a lower-ranked passage
    usually arrives without the context that made it mean something.
    """
    seen: set[str] = set()
    chosen: list[_Unit] = []
    used_prose = 0
    used_points = 0

    for unit in sorted(units, key=lambda item: item.score, reverse=True):
        if unit.score <= 0.0:
            continue

        if unit.is_point:
            if used_points >= MAX_POINT_UNITS:
                continue
        else:
            if used_prose >= MAX_PROSE_UNITS or unit.passage_index >= PROSE_PASSAGE_LIMIT:
                continue

        fingerprint = normalise(unit.text)[:120]
        if fingerprint in seen:
            continue

        seen.add(fingerprint)
        chosen.append(unit)

        if unit.is_point:
            used_points += 1
        else:
            used_prose += 1

        if len(chosen) >= limit:
            break

    chosen.sort(key=lambda item: (item.passage_index, item.position))
    return chosen


def _render(units: list[_Unit]) -> str:
    """Render selected units as prose plus a bullet list, in reading order."""
    prose: list[str] = []
    points: list[str] = []

    for unit in units:
        if unit.is_point:
            marker = _list_marker(unit.text)
            text = unit.text[len(marker) :].strip() if marker else unit.text
            points.append(_clean(text))
        else:
            prose.append(unit.text)

    blocks: list[str] = []

    if prose:
        blocks.append(" ".join(prose))

    if points:
        blocks.append("\n".join(f"- {_clean(point)}" for point in points))

    return "\n\n".join(blocks)


class GroundedProvider(LLMProvider):
    """Assemble an answer from retrieved text, without generating language."""

    name = "grounded-extractive"
    model = "extractive-responder"
    is_generative = False

    def generate(self, request: GenerationRequest) -> str:
        question = (request.question or "").strip()

        # Fall back to the most recent user turn if no question was supplied.
        if not question:
            for turn in reversed(list(request.messages)):
                if turn.role == "user":
                    question = turn.content
                    break

        passages = [passage for passage in request.passages if passage and passage.strip()]
        if not passages:
            return NO_COVERAGE

        units: list[_Unit] = []
        for index, passage in enumerate(passages):
            units.extend(_units_from_passage(passage, index))

        if not units:
            return NO_COVERAGE

        selected = _select(_score(units, question))
        loose_match = not selected

        if loose_match:
            # Material exists but none of it addresses the wording, so present
            # the opening of the best passage and label the match as loose.
            selected = units[:3]

        lead = (
            "The retrieved sources do not match that question closely. "
            "The most relevant passages held by Verdant begin:"
            if loose_match
            else "From the sources Verdant holds on this:"
        )

        return f"{lead}\n\n{_render(selected)}\n\n{NO_PROVIDER_NOTE}"

